server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost
      
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: producto-service
          uri: lb://producto-service
          predicates:
            - Path=/productApi/**
            
        - id: cliente-service
          uri: lb://cliente-service
          predicates:
            - Path=/customerApi/**
            
        - id: proveedor-service
          uri: lb://proveedor-service
          predicates:
            - Path=/supplierApi/**
            
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
            
        - id: proveedor-service
          uri: lb://proveedor-service
          predicates:
            - Path=/**
