server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: gateway
          uri: https://github.com/Alexiz0r0/My-First-Spring-Project
          search-paths:
            - config-data
  application:
    name: config-service
